name: "Delete Tags without Release"
description: "Delete all the Tags of a repository that are not associated to a Release"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Tags
      uses: octokit/request-action@v2.1.0
      id: get_tags
      with:
        route: GET /repos/${{ github.repository }}/tags
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - run: "echo tags: '${{ steps.get_tags.outputs.data }}'"
      shell: bash
    - name: Get Releases
      uses: octokit/request-action@v2.1.0
      id: get_releases
      with:
        route: GET /repos/${{ github.repository }}/releases
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - run: "echo releases: '${{ steps.get_releases.outputs.data }}'"
      shell: bash
    - name: Output test
      shell: bash
      run: |
        echo $(jq .[].name  <<< '${{ steps.get_tags.outputs.data }}')
       
        
      
