name: "Delete Tags without Release"
description: "Delete all the Tags of a repository that are not associated to a Release"
author: "mail@fabriziocacicia.com"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Tags
      uses: octokit/request-action@v2.1.0
      id: get_tags
      with:
        route: GET /repos/${{ github.repository }}/tags
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Get Releases
      uses: octokit/request-action@v2.1.0
      id: get_releases
      with:
        route: GET /repos/${{ github.repository }}/releases
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Find Tags with Releases
      id: find_tags_with_release
      shell: bash
      run: |
        TAGS_WITH_RELEASES=$(jq -c -r .[].tag_name  <<< '${{ steps.get_releases.outputs.data }}')
        echo "::set-output name=VALUES::$TAGS_WITH_RELEASES"
    - name: Delete free Tags
      shell: bash
      run: |
        tags_with_release=$(jq -c -r .[].tag_name  <<< '${{ steps.get_releases.outputs.data }}')
        jq -c -r .[].name  <<< '${{ steps.get_tags.outputs.data }}' | while read -r tag; 
        do 
          if [[ "${{ steps.find_tags_with_release.outputs.values }}" != *"$tag"* ]]; then
            gh api --method DELETE -H "Accept: application/vnd.github+json" "/repos/${{ github.repository }}/git/refs/tags/$tag"
          fi
        done
        
    

        
      
